# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimgle/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimgle/apps/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimgle/data/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimgle/include/dcmtk/dcmimgle/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimgle/libsrc/CMakeLists.txt
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/dan/Documents/xcode/alt/dcmtk-3.6.0 -B/Users/dan/Documents/xcode/alt/dcmtkbin
