# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimage/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimage/apps/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimage/include/dcmtk/dcmimage/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmimage/libsrc/CMakeLists.txt
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/dan/Documents/xcode/alt/dcmtk-3.6.0 -B/Users/dan/Documents/xcode/alt/dcmtkbin
