# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Applications/CMake\ 2.8-8.app/Contents/share/cmake-2.8/Modules/CheckIncludeFile.cmake\
/Users/dan/Documents/xcode/alt/gdcm-2.2.0/Utilities/gdcmexpat/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/gdcm-2.2.0/Utilities/gdcmexpat/expat_config.h.in\
/Users/dan/Documents/xcode/alt/gdcm-2.2.0/Utilities/gdcmexpat/expat_mangle.h.in\
/Users/dan/Documents/xcode/alt/gdcm-2.2.0/Utilities/gdcmexpat/lib/CMakeLists.txt
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/dan/Documents/xcode/alt/gdcm-2.2.0 -B/Users/dan/Documents/xcode/alt/gdcmbin
