# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/oflog/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/oflog/etc/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/oflog/include/dcmtk/oflog/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/oflog/include/dcmtk/oflog/config/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/oflog/include/dcmtk/oflog/helpers/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/oflog/include/dcmtk/oflog/spi/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/oflog/libsrc/CMakeLists.txt
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/dan/Documents/xcode/alt/dcmtk-3.6.0 -B/Users/dan/Documents/xcode/alt/dcmtkbin
