# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmjpls/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmjpls/apps/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmjpls/include/dcmtk/dcmjpls/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmjpls/libcharls/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmjpls/libsrc/CMakeLists.txt
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/dan/Documents/xcode/alt/dcmtk-3.6.0 -B/Users/dan/Documents/xcode/alt/dcmtkbin
