# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/dan/Documents/xcode/alt/gdcm-2.2.0/Utilities/gdcmcharls/CMakeLists.txt
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/dan/Documents/xcode/alt/gdcm-2.2.0 -B/Users/dan/Documents/xcode/alt/gdcmbin
