# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmwlm/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmwlm/apps/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmwlm/data/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmwlm/docs/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmwlm/include/dcmtk/dcmwlm/CMakeLists.txt\
/Users/dan/Documents/xcode/alt/dcmtk-3.6.0/dcmwlm/libsrc/CMakeLists.txt
	/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -H/Users/dan/Documents/xcode/alt/dcmtk-3.6.0 -B/Users/dan/Documents/xcode/alt/dcmtkbin
